thrift:
  port: 7000
  operator:
    host: localhost
    port: 4000
  notify: # 用于下游向上游通信的地址
    host: localhost
    port: 8888
mode: local # 表示执行的方式，使用configMap的方式挂载的配置文件是kubernetes，本地文件中仍然是local模式
mvnDir: /Users/zjchen/.m2/repository
dag:
  prefix: /Users/zjchen/Desktop/CLIC/dag
kubernetes:
  api-server: 10.176.24.160:6443 # 内部使用kubernetes.default.svc
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlZZWHZoeVlJRFFFZDQxUEs3UmRibEk2bHhVelUwTXRzZXpoZ0xjMW8wZHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi0ydmhrZiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjRmMTYwNTEwLWZiZjEtNGE1NC04ZjFmLWU1YjcyZjVkOGMzZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.bOcgdIvIgumPV5ME4o4h_IIRX_ZC9mbCzS84TA_xMOAomdoS22TGM0KPsFq4KaFGmILyvYPPUc9XAYZe3PTLsj2Odwnt8ywrjItGO-w1UzbUFLMsZEqtiZRlQBCO8-J5OSu6SuZxQEkp_Z7jDW2BboqqTPzOEGacRkAyk4fNbEKz_SRcvq0o8diCg_BHf-ve2GrYTZ_VAIQ_uNYADxL-qtJ3iaCUgCDxzxB6U_GjExp90bcucZKPMgP-cD9jY1ZijRpmJJ54wWhrDJXCvOak0qMfUegZKkO9jwdRNnZDmoX8Vk99tmUkdDn2BBHtVvuAYDIQ5tZHaVZLHYc-ACocdQ
  # 添加平台，这里只是本地的配置，k8s中采用configmap配置，需要去deploy中的executor-center-config中添加
  job:
    create: "/apis/batch/v1/namespaces/default/jobs"
  spark:
    create: "/apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications"
  mpi:
    create: "/apis/kubeflow.org/v1/namespaces/mpi-operator/mpijobs"