FROM edwardtang/spark-operator:v3.0.0
WORKDIR /
ADD ./executable-operator/executable-spark/target/executable-spark-1.0-SNAPSHOT-jar-with-dependencies.jar  executable-spark.jar
#CMD java -jar executable-spark.jar