# @author 杜清华
# @since  2020/7/6 11:39
# @version 1.0
# 使用argo创建argo workflow
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: compute-scheduling-flow
spec:
  entrypoint: my-flow
  volumes:
    - name: job-volume
      hostPath:
        path: /home/dqh/codes/k8s_basics/executable-java/data
        type: Directory
  templates:
    - name: my-flow
      dag:
        tasks:
