apiVersion: v1
kind: Pod
metadata:
  name: clic-master
  namespace: argo
spec:
  containers:
    - name: master-template
      image: java-env:v0
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
      args:
        - java -jar /data/jars/clic-master.jar
      volumeMounts:
        - name: nfs-volume
          mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: pvc-nfs