apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-headless
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
