/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fdu.daslab.thrift.schedulercenter;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-06-09")
public enum PluginType implements org.apache.thrift.TEnum {
  SORT_PLUGIN(0),
  FILTER_PLUGIN(1),
  BIND_PLUGIN(2);

  private final int value;

  private PluginType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static PluginType findByValue(int value) { 
    switch (value) {
      case 0:
        return SORT_PLUGIN;
      case 1:
        return FILTER_PLUGIN;
      case 2:
        return BIND_PLUGIN;
      default:
        return null;
    }
  }
}
