# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-datanode
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: datanode
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  ports:
  - name: webhdfs
    port: 50075
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: datanode
    app.kubernetes.io/instance: {{ .Release.Name }}

